# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.20"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.20"
  i386: "ghcr.io/home-assistant/i386-base-python:3.13-alpine3.20"
labels:
  org.opencontainers.image.title: "Battery manager"
  org.opencontainers.image.description: "Manage your home batteries."
  org.opencontainers.image.source: "https://github.com/Local901/battery-management"
  org.opencontainers.image.licenses: "Apache License 2.0"
