# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Battery manager
version: "4.0.1"
slug: batman
description: Manage your home batteries.
url: "https://github.com/Local901/battery-management/"
image: "ghcr.io/local901/{arch}-addon-batman"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
homeassistant_api: true
map:
  - share:rw
options:
  host: 127.1.1.1
  port: 502
  timezone: 0
  delay: 2
  timeout: 5
  minChargePercentage: 0
  control_mode: none
  schedule:
    h00:
      m00: o
    h01:
      m00: o
    h02:
      m00: o
    h03:
      m00: o
    h04:
      m00: o
    h05:
      m00: o
    h06:
      m00: o
    h07:
      m00: o
    h08:
      m00: o
    h09:
      m00: o
    h10:
      m00: o
    h11:
      m00: o
    h12:
      m00: o
    h13:
      m00: o
    h14:
      m00: o
    h15:
      m00: o
    h16:
      m00: o
    h17:
      m00: o
    h18:
      m00: o
    h19:
      m00: o
    h20:
      m00: o
    h21:
      m00: o
    h22:
      m00: o
    h23:
      m00: o
schema:
  host: "match(^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$)"
  port: "int(0,65535)"
  timezone: "int"
  delay: "int(1,)"
  timeout: "int"
  minChargePercentage: "int(0,100)"
  control_mode: "list(none|charge|discharge|schedule)"
  schedule:
    h00:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h01:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h02:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h03:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h04:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h05:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h06:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h07:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h08:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h09:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h10:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h11:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h12:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h13:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h14:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h15:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h16:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h17:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h18:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h19:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h20:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h21:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h22:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
    h23:
      m00: "str"
      m15: "str?"
      m30: "str?"
      m45: "str?"
  chargeState: "str?"
