# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Battery manager
version: "2.0.4"
slug: batman
description: Manage your home batteries.
url: "https://github.com/Local901/battery-management/"
# image: "ghcr.io/local901/{arch}-addon-batman"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
homeassistant_api: true
map:
  - share:rw
options:
  host: 127.1.1.1
  port: 502
  timezone: 0
  delay: 2
  timeout: 5
  control_mode: none
  schedule:
    d0h00: .
    d0h01: .
    d0h02: .
    d0h03: .
    d0h04: .
    d0h05: .
    d0h06: .
    d0h07: .
    d0h08: .
    d0h09: .
    d0h10: .
    d0h11: .
    d0h12: .
    d0h13: .
    d0h14: .
    d0h15: .
    d0h16: .
    d0h17: .
    d0h18: .
    d0h19: .
    d0h20: .
    d0h21: .
    d0h22: .
    d0h23: .
    d1h00: .
    d1h01: .
    d1h02: .
    d1h03: .
    d1h04: .
    d1h05: .
    d1h06: .
    d1h07: .
    d1h08: .
    d1h09: .
    d1h10: .
    d1h11: .
    d1h12: .
    d1h13: .
    d1h14: .
    d1h15: .
    d1h16: .
    d1h17: .
    d1h18: .
    d1h19: .
    d1h20: .
    d1h21: .
    d1h22: .
    d1h23: .
schema:
  host: "match(^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$)"
  port: "int(0,65535)"
  timezone: "int"
  delay: "int(1,)"
  timeout: "int"
  control_mode: "list(none|charge|discharge|schedule)"
  schedule:
    d0h00: "str"
    d0h01: "str"
    d0h02: "str"
    d0h03: "str"
    d0h04: "str"
    d0h05: "str"
    d0h06: "str"
    d0h07: "str"
    d0h08: "str"
    d0h09: "str"
    d0h10: "str"
    d0h11: "str"
    d0h12: "str"
    d0h13: "str"
    d0h14: "str"
    d0h15: "str"
    d0h16: "str"
    d0h17: "str"
    d0h18: "str"
    d0h19: "str"
    d0h20: "str"
    d0h21: "str"
    d0h22: "str"
    d0h23: "str"
    d1h00: "str"
    d1h01: "str"
    d1h02: "str"
    d1h03: "str"
    d1h04: "str"
    d1h05: "str"
    d1h06: "str"
    d1h07: "str"
    d1h08: "str"
    d1h09: "str"
    d1h10: "str"
    d1h11: "str"
    d1h12: "str"
    d1h13: "str"
    d1h14: "str"
    d1h15: "str"
    d1h16: "str"
    d1h17: "str"
    d1h18: "str"
    d1h19: "str"
    d1h20: "str"
    d1h21: "str"
    d1h22: "str"
    d1h23: "str"
