# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Battery manager
version: "3.1.0"
slug: batman
description: Manage your home batteries.
url: "https://github.com/Local901/battery-management/"
image: "ghcr.io/local901/{arch}-addon-batman"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
homeassistant_api: true
map:
  - share:rw
options:
  host: 127.1.1.1
  port: 502
  timezone: 0
  delay: 2
  timeout: 5
  minChargePercentage: 0
  control_mode: none
  schedule:
    h00: o
    h01: o
    h02: o
    h03: o
    h04: o
    h05: o
    h06: o
    h07: o
    h08: o
    h09: o
    h10: o
    h11: o
    h12: o
    h13: o
    h14: o
    h15: o
    h16: o
    h17: o
    h18: o
    h19: o
    h20: o
    h21: o
    h22: o
    h23: o
schema:
  host: "match(^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$)"
  port: "int(0,65535)"
  timezone: "int"
  delay: "int(1,)"
  timeout: "int"
  minChargePercentage: "int(0,100)"
  control_mode: "list(none|charge|discharge|schedule)"
  schedule:
    h00: "str"
    h01: "str"
    h02: "str"
    h03: "str"
    h04: "str"
    h05: "str"
    h06: "str"
    h07: "str"
    h08: "str"
    h09: "str"
    h10: "str"
    h11: "str"
    h12: "str"
    h13: "str"
    h14: "str"
    h15: "str"
    h16: "str"
    h17: "str"
    h18: "str"
    h19: "str"
    h20: "str"
    h21: "str"
    h22: "str"
    h23: "str"
  chargeState: "str?"
