# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Battery manager
version: "0.0.2"
slug: example
description: Manage you home batteries.
url: "https://github.com/Local901/battery-management/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world...!!!"
schema:
  message: "str?"
