# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Battery manager
version: "0.0.3"
slug: example
description: Manage you home batteries.
url: "https://github.com/Local901/battery-management/"
image: "ghcr.io/local901/{arch}-addon-battery-management"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world...!!!"
  host: 192.168.178.181
schema:
  message: "str?"
  host: "match(^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$)"
